apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: application
  name: application
spec:
  containers:
  - image: abdelazizgbr/nodejs-app
    name: application
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
